const AUTH_TOKEN = "@token";

const LOGGED_OUT = "LOGGED_OUT";
const ERROR = "ERROR";
const SUCCESS = "SUCCESS";
const STARTED = "STARTED";
const BOOTSTRAP = "BOOTSTRAP";

const STATUS_REJECTED = "STATUS_REJECTED";
const STATUS_RESOLVED = "STATUS_RESOLVED";
const STATUS_PENDING = "STATUS_PENDING";
const STATUS_IDLE = "STATUS_IDLE";
const STATUS_BOOTSTRAPPING = "STATUS_BOOTSTRAPPING";

export {
  AUTH_TOKEN,
  LOGGED_OUT,
  ERROR,
  SUCCESS,
  BOOTSTRAP,
  STARTED,
  STATUS_RESOLVED,
  STATUS_REJECTED,
  STATUS_PENDING,
  STATUS_IDLE,
  STATUS_BOOTSTRAPPING,
};
